apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-nfs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.100.126
    path: /exports/db
  persistentVolumeReclaimPolicy: Retain
